import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import "./globals.css";
import "./main.css";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
    <html lang="en">
      <body
        className={`outfit-regular antialiased`}
      >
        <Navbar session={session} />
        {children}
      </body>
    </html>
  );
}
